# Command name for command-line interface
CLI_NAME = 'netgens'

# Default arguments
DEFAULT_GENERATIONS = 1000
DEFAULT_SAMPLE_RATE = .0006
DEFAULT_BINS = 100
DEFAULT_TOLERANCE = 0.1
DEFAULT_GEN_TYPE = 'exo'
DEFAULT_NODES = 1000
DEFAULT_EDGES = 10000
